import { Scenario } from "../interfaces/scenario.interface";
import { mockProducts } from "./mock-products";
import { mockUsers } from "./mock-users";

export const mockScenarios: Scenario[] = [
    {
        id: 1,
        date: new Date(),
        user: mockUsers[0],
        description: "Only Cash In",
        transactions: [
            {
                rowIndex: 0,
                direction: "In",
                type: "Cash",
                amount: 325.15,
            }
        ],
        currentRate: 89.89,
        total24kProductIn: 0,
        total24kProductOut: 0,
        total24kScrapIn: 0,
        total24kScrapOut: 0,
        total24kIn: 0,
        total24kOut: 0,
        totalCashIn: 325.15,
        totalCashOut: 0,
        totalBankIn: 0,
        totalBankOut: 0,
    },
    {
        id: 2,
        date: new Date(),
        user: mockUsers[0],
        description: "Only Cash Out",
        transactions: [
            {
                rowIndex: 0,
                direction: "Out",
                type: "Cash",
                amount: 415,
            }
        ],
        currentRate: 89.89,
        total24kProductIn: 0,
        total24kProductOut: 0,
        total24kScrapIn: 0,
        total24kScrapOut: 0,
        total24kIn: 0,
        total24kOut: 0,
        totalCashIn: 0,
        totalCashOut: 415,
        totalBankIn: 0,
        totalBankOut: 0,
    },
    {
        id: 3,
        date: new Date(),
        user: mockUsers[0],
        description: "Only Bank In",
        transactions: [
            {
                rowIndex: 0,
                direction: "In",
                type: "Bank",
                amount: 250.50,
            }
        ],
        currentRate: 89.89,
        total24kProductIn: 0,
        total24kProductOut: 0,
        total24kScrapIn: 0,
        total24kScrapOut: 0,
        total24kIn: 0,
        total24kOut: 0,
        totalCashIn: 0,
        totalCashOut: 0,
        totalBankIn: 250.50,
        totalBankOut: 0,
    },
    {
        id: 4,
        date: new Date(),
        user: mockUsers[0],
        description: "Only Bank Out",
        transactions: [
            {
                rowIndex: 0,
                direction: "Out",
                type: "Bank",
                amount: 125.25,
            }
        ],
        currentRate: 89.89,
        total24kProductIn: 0,
        total24kProductOut: 0,
        total24kScrapIn: 0,
        total24kScrapOut: 0,
        total24kIn: 0,
        total24kOut: 0,
        totalCashIn: 0,
        totalCashOut: 0,
        totalBankIn: 0,
        totalBankOut: 125.25,
    },
    {
        id: 5,
        date: new Date(),
        user: mockUsers[0],
        description: "Only Cash Out  and Bank In",
        transactions: [
            {
                rowIndex: 0,
                direction: "Out",
                type: "Cash",
                amount: 410,
            },
            {
                rowIndex: 1,
                direction: "In",
                type: "Bank",
                amount: 525,
            }
        ],
        currentRate: 89.89,
        total24kProductIn: 0,
        total24kProductOut: 0,
        total24kScrapIn: 0,
        total24kScrapOut: 0,
        total24kIn: 0,
        total24kOut: 0,
        totalCashIn: 0,
        totalCashOut: 410,
        totalBankIn: 525,
        totalBankOut: 0,
    },
    {
        id: 6,
        date: new Date(),
        user: mockUsers[0],
        description: "Product Out and Cash In",
        transactions: [
            {
                rowIndex: 0,
                direction: "Out",
                type: "Product",
                product: mockProducts[0],
                quantity: 1,
                total24KWeight: 1.605,
            },
            {
                rowIndex: 1,
                direction: "In",
                type: "Cash",
                amount: 325.15,
            }
        ],
        currentRate: 89.89,
        total24kProductIn: 0,
        total24kProductOut: 1.605,
        total24kScrapIn: 0,
        total24kScrapOut: 0,
        total24kIn: 0,
        total24kOut: 1.605,
        totalCashIn: 325.15,
        totalCashOut: 0,
        totalBankIn: 0,
        totalBankOut: 0,
    },
    {
        id: 7,
        date: new Date(),
        user: mockUsers[0],
        description: "Product In and Cash Out   ",
        transactions: [
            {
                rowIndex: 0,
                direction: "In",
                type: "Product",
                product: mockProducts[0],
                quantity: 1,
                total24KWeight: 1.605,
            },
            {
                rowIndex: 1,
                direction: "Out",
                type: "Cash",
                amount: 325.15,
            }
        ],
        currentRate: 89.89,
        total24kProductIn: 1.605,
        total24kProductOut: 0,
        total24kScrapIn: 0,
        total24kScrapOut: 0,
        total24kIn: 1.605,
        total24kOut: 0,
        totalCashIn: 0,
        totalCashOut: 325.15,
        totalBankIn: 0,
        totalBankOut: 0,
    },
    {
        id: 8,
        date: new Date(),
        user: mockUsers[0],
        description: "Scrap Out and Product In",
        transactions: [ 
            {
                rowIndex: 0,
                direction: "Out",
                type: "Scrap",
                weight: 1.75,
                carat: 22,
                total24KWeight: 1.605,
            },
            {
                rowIndex: 1,
                direction: "In",
                type: "Product",
                product: mockProducts[0],
                quantity: 1,
                total24KWeight: 1.605,
            }
        ],
        currentRate: 89.89,
        total24kProductIn: 1.605,
        total24kProductOut: 0,
        total24kScrapIn: 0,
        total24kScrapOut: 1.605,
        total24kIn: 0,
        total24kOut: 0,
        totalCashIn: 0,
        totalCashOut: 0,
        totalBankIn: 0,
        totalBankOut: 0,
    }
]   
